{% set name = "PEKA" %}
{% set version = "0.1.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/ulelab/peka/archive/refs/tags/v{{ version }}.tar.gz"
  sha256: 6166d386dccd276da989dc87d9ffa8c206f25867c2b0cc45c03fd2e46335b82b

build:
  number: 0
  entry_points:
    - peka = peka:cli
  script: "{{ PYTHON }} -m pip install . -vv --ignore-installed --no-deps"
  noarch: python

requirements:
  host:
    - pip
    - python==3.7
  run:
    - python==3.7
    - matplotlib-base==3.1.2
    - numpy==1.17.4
    - pybedtools==0.8.0
    - scipy==1.6.2
    - seaborn==0.9.0
    - plumbum==1.6.8
    - scikit-learn==0.21.3
    - pandas==0.24.2
    - textdistance==4.1.3

test:
  commands:
    - peka --help

about:
  home: "https://github.com/ulelab/peka"
  license: GPL-3.0
  license_file: LICENSE
  summary: "Analysis of kmers located around locations of interest"

extra:
  recipe-maintainers:
    - marc-jones
    - codeprimate123
